[package]
name = "bevy_macros_compile_fail_tests"
version = "0.1.0"
description = "Compile fail tests for Bevy Engine's various macros"
publish = false
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
rust-version.workspace = true

[dependencies]
bevy_derive = { path = "../bevy_derive" }
trybuild = "1.0.71"
