[package]
name = "bevy_asset_macros"
description = "Derive implementations for bevy_asset"
keywords = ["bevy", "assets", "derive", "macros"]
categories.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
bevy_macro_utils = { path = "../../bevy_macro_utils", version = "0.12.0-dev" }

syn = "2.0"
proc-macro2 = "1.0"
quote = "1.0"
