[package]
name = "bevy_tasks"
description = "A task executor for Bevy Engine"
keywords = ["bevy", "task executor", "tasks"]
categories.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
rust-version.workspace = true

[features]
multi-threaded = []

[dependencies]
futures-lite = "1.4.0"
async-executor = "1.3.0"
async-channel = "1.4.2"
async-task = "4.2.0"
concurrent-queue = "2.0.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"

[dev-dependencies]
instant = { version = "0.1", features = ["wasm-bindgen"] }
