[package]
name = "bevy_reflect_derive"
description = "Derive implementations for bevy_reflect"
keywords = ["bevy", "derive", "reflect", "macros"]
categories.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[features]
default = []
# When enabled, allows documentation comments to be processed by the reflection macros
documentation = []

[dependencies]
bevy_macro_utils = { path = "../../bevy_macro_utils", version = "0.12.0-dev" }

syn = { version = "2.0", features = ["full"] }
proc-macro2 = "1.0"
quote = "1.0"
uuid = { version = "1.1", features = ["v4"] }
bit-set = "0.5.2"
