[package]
name = "bevy_transform"
description = "Provides transform functionality for Bevy Engine"
keywords = ["bevy", "transform"]
categories.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
rust-version.workspace = true

[dependencies]
# bevy
bevy_app = { path = "../bevy_app", version = "0.12.0-dev" }
bevy_ecs = { path = "../bevy_ecs", version = "0.12.0-dev", features = [
    "bevy_reflect",
] }
bevy_hierarchy = { path = "../bevy_hierarchy", version = "0.12.0-dev" }
bevy_math = { path = "../bevy_math", version = "0.12.0-dev" }
bevy_reflect = { path = "../bevy_reflect", version = "0.12.0-dev", features = [
    "bevy",
] }
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
bevy_tasks = { path = "../bevy_tasks", version = "0.12.0-dev" }

[features]
serialize = ["dep:serde", "bevy_math/serialize"]
