[package]
name = "bevy_core"
description = "Provides core functionality for Bevy Engine"
keywords = ["bevy", "core"]
categories.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
rust-version.workspace = true

[dependencies]
# bevy
bevy_app = { path = "../bevy_app", version = "0.12.0-dev", features = [
    "bevy_reflect",
] }
bevy_ecs = { path = "../bevy_ecs", version = "0.12.0-dev", features = [
    "bevy_reflect",
] }
bevy_math = { path = "../bevy_math", version = "0.12.0-dev" }
bevy_reflect = { path = "../bevy_reflect", version = "0.12.0-dev", features = [
    "bevy",
] }
bevy_tasks = { path = "../bevy_tasks", version = "0.12.0-dev" }
bevy_utils = { path = "../bevy_utils", version = "0.12.0-dev" }

# other
bytemuck = "1.5"
serde = { version = "1.0", optional = true }

[features]
serialize = ["dep:serde"]

[dev-dependencies]
crossbeam-channel = "0.5.0"
