[package]
name = "bevy_window"
description = "Provides windowing functionality for Bevy Engine"
keywords = ["bevy", "window", "windowing"]
categories.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
rust-version.workspace = true

[features]
default = []
serialize = ["serde"]

[dependencies]
# bevy
bevy_app = { path = "../bevy_app", version = "0.12.0-dev" }
bevy_ecs = { path = "../bevy_ecs", version = "0.12.0-dev" }
bevy_math = { path = "../bevy_math", version = "0.12.0-dev" }
bevy_reflect = { path = "../bevy_reflect", version = "0.12.0-dev", features = [
    "glam",
] }
bevy_utils = { path = "../bevy_utils", version = "0.12.0-dev" }
# Used for close_on_esc
bevy_input = { path = "../bevy_input", version = "0.12.0-dev" }
raw-window-handle = "0.5"

# other
serde = { version = "1.0", features = ["derive"], optional = true }
