[package]
name = "bevy_math"
description = "Provides math functionality for Bevy Engine"
keywords = ["bevy", "math"]
categories = ["game-development", "mathematics"]
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
rust-version.workspace = true

[dependencies]
glam = { version = "0.24.1", features = ["bytemuck"] }
serde = { version = "1", features = ["derive"], optional = true }

[features]
serialize = ["dep:serde", "glam/serde"]
# Enable interoperation of glam types with mint-compatible libraries
mint = ["glam/mint"]
# Enable assertions to check the validity of parameters passed to glam
glam_assert = ["glam/glam-assert"]
