[package]
name = "bevy_log"
description = "Provides logging for Bevy Engine"
keywords = ["bevy", "logging"]
categories = ["game-development", "development-tools::debugging"]
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
rust-version.workspace = true

[features]
trace = ["tracing-error"]
trace_tracy_memory = ["dep:tracy-client"]

[dependencies]
bevy_app = { path = "../bevy_app", version = "0.12.0-dev" }
bevy_utils = { path = "../bevy_utils", version = "0.12.0-dev" }
bevy_ecs = { path = "../bevy_ecs", version = "0.12.0-dev" }

tracing-subscriber = { version = "0.3.1", features = [
    "registry",
    "env-filter",
] }
tracing-chrome = { version = "0.7.0", optional = true }
tracing-tracy = { version = "0.10.0", optional = true }
tracing-log = "0.1.2"
tracing-error = { version = "0.2.0", optional = true }
tracy-client = { version = "0.16", optional = true }

[target.'cfg(target_os = "android")'.dependencies]
android_log-sys = "0.3.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2.1"
