[package]
name = "bevy_encase_derive"
description = "Bevy derive macro for encase"
keywords = ["bevy", "encase", "derive"]
categories.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
bevy_macro_utils = { path = "../bevy_macro_utils", version = "0.12.0-dev" }
encase_derive_impl = "0.6.1"
