[package]
name = "bevy_utils_proc_macros"
description = "Bevy Utils Proc Macros"
keywords = ["bevy", "utils", "macros", "proc"]
categories.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"
