[package]
name = "bevy_reflect_compile_fail_tests"
version = "0.1.0"
description = "Compile fail tests for Bevy Engine's reflection system"
publish = false
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
rust-version.workspace = true

[dev-dependencies]
bevy_reflect = { path = "../bevy_reflect" }
trybuild = "1.0.71"
