[package]
name = "bevy_ptr"
description = "Utilities for working with untyped pointers in a more safe way"
keywords = ["bevy", "no_std", "ptr"]
categories.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
rust-version.workspace = true

[dependencies]
