[package]
name = "bevy_input"
description = "Provides input functionality for Bevy Engine"
keywords = ["bevy", "input"]
categories.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
rust-version.workspace = true

[features]
default = []
serialize = ["serde"]

[dependencies]
# bevy
bevy_app = { path = "../bevy_app", version = "0.12.0-dev" }
bevy_ecs = { path = "../bevy_ecs", version = "0.12.0-dev" }
bevy_math = { path = "../bevy_math", version = "0.12.0-dev" }
bevy_utils = { path = "../bevy_utils", version = "0.12.0-dev" }
bevy_reflect = { path = "../bevy_reflect", version = "0.12.0-dev", features = [
    "glam",
] }

# other
serde = { version = "1", features = ["derive"], optional = true }
thiserror = "1.0"

[dev-dependencies]
bevy = { path = "../../", version = "0.12.0-dev" }
