[package]
name = "bevy_ecs_compile_fail_tests"
description = "Compile fail tests for Bevy Engine's entity component system"
publish = false
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
rust-version.workspace = true

[dev-dependencies]
bevy_ecs = { path = "../bevy_ecs" }
trybuild = "1.0.71"
