[package]
name = "bevy_macro_utils"
description = "A collection of utils for Bevy Engine"
keywords = ["bevy", "macro", "utils"]
categories.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
rust-version.workspace = true

[dependencies]
toml_edit = "0.19"
syn = "2.0"
quote = "1.0"
rustc-hash = "1.0"
