[package]
name = "bevy_dylib"
description = "Force the Bevy Engine to be dynamically linked for faster linking"
keywords = ["bevy", "dylib"]
categories.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
readme.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["dylib"]

[dependencies]
bevy_internal = { path = "../bevy_internal", version = "0.12.0-dev", default-features = false }
